version: '3.1'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: >
      sh -c "yarn install && yarn prisma migrate dev && yarn prisma generate && npx ts-node prisma/seed.ts && yarn dev"
    restart: always
    networks:
      - my-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
